apiVersion: v1
kind: Pod
metadata:
  name: my-mongo-pod
  labels:
    app: mongodb 
spec:
  containers:
    - name: my-mongo-pod
      image: mongo:latest
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  volumes:
    - name: mongodb-storage
      persistentVolumeClaim:
        claimName: my-mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort