version: '1'

services:
  app:
      build: .
      ports:
        - "3000:3000"
      healthcheck:
        test: ["CMD", "bash", "-c", "curl -f http://localhost:3000/ || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 5s