apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
      - name: mikroserwis-a
        image: cprajwowski/lab10-zad1-mikroserwis_a:v2
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-a
spec:
  type: LoadBalancer
  selector:
    app: mikroserwis-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
