version: '4.1.13'
services:
  db:
    ports:
      - "27019:27017"
    networks:
      - net_A
    image: mongo:4.1.13
    volumes:
    - bazamongo:/data/db

networks:
    net_A:
      external: false
      name: net_A

volumes:
  bazamongo:
