apiVersion: v1
kind: Service
metadata:
  name: my-nginx-nodeport

spec: 
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  
  selector:
    app: myapp
    type: frontend
