apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    volumeMounts:
    - name: mongodb-storage
      mountPath: /data/db
      
  volumes:
  - name: mongodb-storage
    persistentVolumeClaim:
      claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017