version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - net_zad2
    container_name: redis

  postgres:
    image: "postgres:13-alpine"
    networks:
      - net_zad2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  myapp:
    build: .
    ports:
      - "3000:3000"
    container_name: myapp
    depends_on:
      - redis
      - postgres
    networks:
      - net_zad2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - myapp
    networks:
      - net_zad2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  net_zad2:
    external: false
    name: net_zad2

volumes:
  postgres-data:
