version: '4.1.13'
services:
  db:
    build:
    ports:
      - "27019:27017"
    networks:
      - net_A
    image: mongodb
    volumes:
    - ./elo/:/data/db

networks:
    net_A:
      external: false
      name: net_A

